Refactor bash scripts + GBT current proj scripts
    - Refactor some bash script to default shell scripts
    - Added new features to the GBT current project
        - project TODO List (MOD+t)
        - project screenshots (MOD+Control+Print Screen)
        - 'gbtcd' to cd to project

diff --git a/.scripts/other/todo b/.scripts/other/todo
--- a/.scripts/other/todo
+++ b/.scripts/other/todo
@@ -1,30 +1,65 @@
-#!/bin/bash
+#!/bin/sh
 #
 # Write/remove a task to do later.
 #
 # Select an existing entry to remove it from the file, or type a new entry to
 # add it.
 #
-# source:https://tools.suckless.org/dmenu/scripts/todo
+# original:https://tools.suckless.org/dmenu/scripts/todo
 
-file="$SCRIPTS/.config/.todo"
-touch "$file"
-height=$(wc -l "$file" | awk '{print $1}')
+todo_file="$SCRIPTS/.config/.todo"
+
+print_help () { echo "TODO list."
+    echo "Calling it with no arguments will start the default todo list."
+    printf "\t -l, --list         Specify the list to use\n"
+    printf "\t -h, --help         Prints this help menu\n"
+}
+
+while [ $# -gt 0 ]
+do
+    todo_key="$1"
+
+    case $todo_key in
+        -l|--list)
+        todo_file="$2"
+        shift # past argument
+        shift # past value
+        ;;
+        -h|--help)
+        shift # past argument
+        print_help
+        exit 0
+        ;;
+        *)
+        echo "Invalid argument '$1'."
+        echo "For more help use argument -h or --help."
+        shift # past argument
+        exit 1
+        ;;
+    esac
+done
+
+[ -d "$todo_file" ] && notify-send --urgency=critical -t 2000 "ERROR" "'$todo_file' is a directory" && exit 1
+
+[ ! -f "$todo_file" ] && notify-send -t 2000 "New Todo List" "New list was created at '$todo_file'"
+
+touch "$todo_file"
+height=$(wc -l "$todo_file" | awk '{print $1}')
 prompt="Add/delete a task: "
 
-cmd=$(dmenu -l "$height" -p "$prompt" "$@" < "$file")
+cmd=$(sort "$todo_file" | dmenu -l "$height" -p "$prompt")
 while [ -n "$cmd" ]; do
- 	if grep -q "^$cmd\$" "$file"; then
+ 	if grep -q "^$cmd\$" "$todo_file"; then
         tmpfile=$(mktemp)
-	    grep -v "^$cmd\$" "$file" > "$tmpfile"
-		mv "$tmpfile" "$file"
+	    grep -v "^$cmd\$" "$todo_file" > "$tmpfile"
+		mv "$tmpfile" "$todo_file"
         height=$(( height - 1 ))
  	else
-		echo "$cmd" >> "$file"
+		echo "$cmd" >> "$todo_file"
 		height=$(( height + 1 ))
  	fi
 
-	cmd=$(dmenu -l "$height" -p "$prompt" "$@" < "$file")
+    cmd=$(sort "$todo_file" | dmenu -l "$height" -p "$prompt")
 done
 
 exit 0
